"""updated review and doghouse models

Revision ID: debb2f29c650
Revises: 003cd5a026a7
Create Date: 2023-10-05 18:49:15.530948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debb2f29c650'
down_revision = '003cd5a026a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doghouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_booked', sa.String(length=150), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=150), autoincrement=False, nullable=True))

    with op.batch_alter_table('doghouses', schema=None) as batch_op:
        batch_op.drop_column('is_booked')

    # ### end Alembic commands ###
